export const API_ENDPOINTS = {
    GET_SESSION: "/end_user/v1/get-session",
    VERIFY_AUTH_TOKEN: "/end_user/v1/verify-auth-token",
    QUERY_SOLVER: "/end_user/v2/code-gen/solve-user-query",
    STORE_AUTH_TOKEN: "/v1/auth/store_token",
    LOAD_AUTH_TOKEN: "/v1/auth/load_token",
    RELEVANT_CHUNKS: "/v1/relevant_chunks",
    UPDATE_VECTOR_DB: "/v1/update_chunks",
    PAST_SESSIONS: "/end_user/history/v1/sessions",
    PAST_CHATS: "/end_user/history/v1/chats",
    DELETE_SESSION: "/end_user/history/v1/delete_session",
    GENERATE_INLINE_EDIT: "/end_user/query_solver/v1/generate-inline-edit",
    GET_INLINE_EDIT_RESULT: "/end_user/query_solver/v1/get-inline-edit-result",
    DIFF_APPLIER : "/v1/diff-applicator/apply-unified-diff",
    BATCH_CHUNKS_SEARCH : "/v1/batch_chunks_search",
    RELEVANT_CHAT_HISTORY: "/end_user/v1/history/relevant-chat-history",
}